on:
  workflow_dispatch:
  push:

env:
  REPO: champtitles/terraform-aws-lambda
  SHA: ${{ github.sha }}
  DOCKER_USERNAME: champtitles
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  example-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.2.0
        with:
          context: test/helper_files
          push: true
          tags: |
            ${{ env.REPO }}:${{ env.SHA }}